title: TheNovusOrbis
description: Welcome to the library of methods where you can sort, filter and check everything to get trustworthy information
minima:
  skin: auto
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
paginate: 10
